export const ENABLE_LOADING = "ENABLE_LOADING";
export const DISABLE_LOADING = "DISABLE_LOADING";
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
export const REGISTER_USER = " REGISTER_USER";
export const LOGIN_USER = " LOGIN_USER";
export const FETCH_SOURCES = "FETCH_SOURCES";
export const RECEIVE_SOURCES = "RECEIVE_SOURCES";